### ISSUE TITLE
Pipeline sparkSend: credentials not found

### ISSUE THREAD

**Issue by cpolzer** [jenkinsci/cisco-spark-notifier-plugin#4]
Hi,

when trying to use sparkSend in my pipeline, my credenitals are not found.

Log:
```
Pipeline] { (Notify  spark)
[Pipeline] sparkSend
Sending message to spark space: 5cf****************************
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
ERROR: No credentials found
```

The credentials are stored in global namespace. Also when using the pipeline "pipeline-syntax/" helper, no credentials are listed, but I have a lot of them in use anywhere else.

Versions in use:
Jenkins ver. 2.19.4
Cisco Spark Notifier 1.1.0

Any hints?

**Comment by cpolzer** [comment]
I might have figured it out: As decoumented in the wiki, create a secret text credential with a spark bot's token. but now in my test i get the message 

> Could not send message because of an unknown issue; please file an issue

??

**Comment by taylorp36** [comment]
Ruh roh, did you figure out the issue causing that "Could not send message because of an unknown issue; please file an issue" ? If so, what was the resolution? I will start adding common pitfalls to the wiki. In the near future, I'll also put the exception contents in the jenkins console to help debug further.

**Comment by cpolzer** [comment]
Yes I think it was corporate proxy related.

**Comment by cpolzer** [comment]
Will check that out as soon the proxy has been configured
